# Generated by Django 5.0.4 on 2024-08-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='description',
            new_name='secondary_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='detail',
        ),
    ]
